export const sportsSticks = [
  "badminton",
  "tennis",
  "table-tennis",
  "squash",
  "racquetball",
  "paddle-tennis",
  "paleta-fronton ",
  "beach tennis",
  "soft-tennis",
  "basque-ball",
  "valencian-ball",
  "golf",
  "croquet",
  "hockey",
  "bandy",
  "floorball",
  "polo",
  "bikepolo",
  "baseball",
  "cricket",
  "softball",
  "lacrosse",
  "polocrosse",
  "billiards",
];

export const sportsCycling = [
  "road-cycling",
  "track-cycling",
  "mountain-biking",
  "bmx",
  "cyclocross ",
  "trial",
  "artistic-cycling",
  "cyclobol",
  "mountain-unicycles",
  "unicycle-trial",
  "unicycle-hockey",
];

export const waterSports = [
  "swimming",
  "synchronized-swimming",
  "jumps",
  "waterpolo",
  "candle",
  "canoeing",
  "remo",
  "rafting",
  "water-skiing",
  "surf",
  "bodyboarding",
  "windsurfing",
  "kitesurfing",
  "waterbasket",
  "watervoley",
  "kayak-polo",
  "powerboats",
  "diving",
  "underwater-hockey",
  "wakeboard",
  "hydrospeed",
];

export const motorSports = [
  "rally-raid",
  "karting",
  "rally",
  "speed-​​racing",
  "drifting",
  "spikes",
  "destruction-races",
  "autoslalom",
  "rallycross",
  "autocross",
  "speed-​​motorcycling",
  "motocross",
  "enduro",
  "endurocross",
  "freestyle",
  "supercross",
  "sidecarcross",
  "speedway",
  "supermoto",
  "superquad",
  "snowcross",
  "speed-​​boating",
  "motonautics-resistance",
  "motonautical-rally",
  "drag-boat-race",
];

export const combinedTests = [
  "triathlon",
  "modern-pentathlon",
  "heptathlon",
  "decathlon",
  "aquathlon",
  "duathlon",
  "biathlon",
  "ski-archery",
  "nordic-combined",
  "marathon",
  "iron-man",
  "ultraman",
  "spartan",
];

export const athletics = [
  "athletic-march",
  "hurdles-racing",
  "speed-races",
  "mid-range-races",
  "long-distance-racing",
  "cross-country",
  "throws",
  "athletic-jump",
];

export const gymnastics = [
  "female-artistic-gymnastics",
  "male-artistic-gymnastics",
  "rhythmic-gymnastics",
  "aerobic-gymnastics",
  "acrobatic-gymnastics",
  "trampoline-gymnastics",
];
export const winterSports = [
  "figure-skating",
  "speed-skating",
  "synchronized-skating",
  "alpine-ski",
  "cross-country-ski",
  "acrobatic-ski",
  "sky-jump",
  "ski-flying",
  "telemark",
  "skijóring",
  "skiboarding",
  "skibobbing",
  "skeleton-sled",
  "bobsleig-sled",
  "luge-sled",
  "airboard-sled",
  "sled-dog-racing",
  "snowboard-freestyle",
  "snowboard-freeride",
  "parallel-slalom-snowboard",
  "snowboard-boardercross",
  "mountain-snowboard",
  "snowboard-snowkiting",
  "freestyle-snowmobile",
  "snowcross-snowmobile",
  "cross-country-snowmobile",
  "snowmobile-hill-climbing",
];
export const combatSports = [
  "fencing",
  "boxing",
  "judo",
  "karate",
  "taekwondo",
  "olympic-wrestling",
  "greco-roman-fight",
  "professional-wrestling",
  "kick-boxing",
  "jiu-jitsu",
  "muay-thai",
  "full-contact",
  "kung-fu",
  "sumo",
  "tai-chi",
  "sambo",
  "eskrima",
  "fight-leonesa",
  "canarian-wrestling",
  "mixed-martial-arts",
  "kendo",
  "savate",
  "lethwei",
  "proresu",
  "shoot-wrestling",
  "shoot-fighting",
  "saint-da",
  "yagli-gures",
  "capoeira",
  "kenpo",
  "hapkido",
  "pa-kua-chang",
  "ninjutsu",
  "aikido",
  "kenjutsu",
  "wing chun",
  "nanbudo",
  "chess-boxing",
  "pencak-silat",
  "iaido",
  "jeet-kune-do",
  "tangsudo",
  "taijutsu",
  "side",
  "schewingen",
  "choy-li-fat",
  "ssirum",
  "bojutsu",
  "shorinji kempo",
  "kuntao",
  "hakko-ryu",
  "gatka",
  "gouren",
  "bokator",
  "glima",
];

export const teamSports = [
  "football",
  "beach-soccer",
  "futsal",
  "basketball",
  "volleyball",
  "beach-volleyball",
  "water-polo",
  "waterbasket",
  "handball",
  "beach-handball",
  "handball-at-11",
  "rugby",
  "beach-rugby",
  "baseball",
  "hockey-grass",
  "ice-hockey",
  "hockey-skates",
  "inline-roller-hockey",
  "indoor-hockey",
  "beach-hockey",
  "unicycle-hockey",
  "afootball",
  "softball",
  "lacrosse",
  "cricket",
  "tennikoit",
  "curling",
  "petanque",
  "bowls",
  "bowling",
  "australian-football",
  "gaelic-football",
  "pole",
  "polocrosse",
  "kayak-polo",
  "bike-polo",
  "padbol",
  "soccer-tennis",
  "futvolley",
  "tchoukball",
  "showbol",
  "bandy",
  "kickball",
  "slamball",
  "korfball",
  "kronum",
  "floorball",
  "bossaball",
  "netball",
  "sepak-takraw",
  "broomball",
  "hurling",
  "shinty",
  "camogie",
  "indiaca",
  "pesapallo",
  "ultimate",
  "wallyball",
  "wiffle-ball",
  "underwater-football",
  "underwater-hockey",
  "underwater-rugby",
];
export const strengthSports = [
  "weightlifting",
  "athletics-strength",
  "powerlifting",
  "grip-force",
  "rope-game",
  "stone-lifting",
  "press",
  "climbing",
  "body-building",
  "log-cut",
];
export const tableSports = [];
export const animalSports = [];

export const precisionSports = [
  "sports-shot",
  "archery",
  "field-archery",
  "darts",
  "golf",
  "footgolf",
  "bowling",
  "curling",
  "billiards",
  "croquet",
  "gateball",
  "petanque",
  "bowls",
  "bowls",
  "horseshoe",
  "frog-or-toad",
  "knife-throw",
  "bald-spot",
  "laser-tag",
  "paintball",
  "airsoft",
];

export const sports = sportsSticks.concat(
  sportsCycling,
  waterSports,
  motorSports,
  combinedTests,
  athletics,
  gymnastics,
  winterSports,
  combatSports,
  teamSports,
  strengthSports,
  tableSports,
  animalSports,
  precisionSports
);
// /**
//  * Deportes disponibles
//  */
// export const sports = [
//   "speed-​​motorcycling",
//   "motocross",
//   "enduro",
//   "endurocross",
//   "freestyle",
//   "supercross",
//   "sidecarcross",
//   "speedway",
//   "supermoto",
//   "superquad",
//   "snowcross",
//   "speed-​​boating",
//   "motonautics-resistance",
//   "motonautical-rally",
//   "drag-boat-race",
//   "rally-raid",
//   "karting",
//   "rally",
//   "speed-​​racing",
//   "drifting",
//   "spikes",
//   "destruction-races",
//   "autoslalom",
//   "rallycross",
//   "autocross",
//   "swimming",
//   "synchronized-swimming",
//   "jumps",
//   "waterpolo",
//   "candle",
//   "canoeing",
//   "remo",
//   "rafting",
//   "water-skiing",
//   "surf",
//   "bodyboarding",
//   "windsurfing",
//   "kitesurfing",
//   "waterbasket",
//   "watervoley",
//   "kayak-polo",
//   "powerboats",
//   "diving",
//   "underwater-hockey",
//   "wakeboard",
//   "hydrospeed",
//   "road-cycling",
//   "track-cycling",
//   "mountain-biking",
//   "bmx",
//   "cyclocross ",
//   "trial",
//   "artistic-cycling",
//   "cyclobol",
//   "mountain-unicycles",
//   "unicycle-trial",
//   "unicycle-hockey",
//   "badminton",
//   "tennis",
//   "table-tennis",
//   "squash",
//   "racquetball",
//   "paddle-tennis",
//   "paleta-fronton ",
//   "beach tennis",
//   "soft-tennis",
//   "basque-ball",
//   "valencian-ball",
//   "golf",
//   "croquet",
//   "hockey",
//   "bandy",
//   "floorball",
//   "polo",
//   "bikepolo",
//   "baseball",
//   "cricket",
//   "softball",
//   "lacrosse",
//   "polocrosse",
//   "billiards",
//   "triathlon",
//   "modern-pentathlon",
//   "heptathlon",
//   "decathlon",
//   "aquathlon",
//   "duathlon",
//   "biathlon",
//   "ski-archery",
//   "nordic-combined",
//   "marathon",
//   "iron-man",
//   "ultraman",
//   "spartan",
//   "athletic-march",
//   "hurdles-racing",
//   "speed-races",
//   "mid-range-races",
//   "long-distance-racing",
//   "cross-country",
//   "throws",
//   "athletic-jump",
//   "sports-shot",
//   "archery",
//   "field-archery",
//   "darts",
//   "golf",
//   "footgolf",
//   "bowling",
//   "curling",
//   "billiards",
//   "croquet",
//   "gateball",
//   "petanque",
//   "bowls",
//   "bowls",
//   "horseshoe",
//   "frog-or-toad",
//   "knife-throw",
//   "bald-spot",
//   "laser-tag",
//   "paintball",
//   "airsoft",
//   "female-artistic-gymnastics",
//   "male-artistic-gymnastics",
//   "rhythmic-gymnastics",
//   "aerobic-gymnastics",
//   "acrobatic-gymnastics",
//   "trampoline-gymnastics",
//   "figure-skating",
//   "speed-skating",
//   "synchronized-skating",
//   "alpine-ski",
//   "cross-country-ski",
//   "acrobatic-ski",
//   "sky-jump",
//   "ski-flying",
//   "telemark",
//   "skijóring",
//   "skiboarding",
//   "skibobbing",
//   "skeleton-sled",
//   "bobsleig-sled",
//   "luge-sled",
//   "airboard-sled",
//   "sled-dog-racing",
//   "snowboard-freestyle",
//   "snowboard-freeride",
//   "parallel-slalom-snowboard",
//   "snowboard-boardercross",
//   "mountain-snowboard",
//   "snowboard-snowkiting",
//   "freestyle-snowmobile",
//   "snowcross-snowmobile",
//   "cross-country-snowmobile",
//   "snowmobile-hill-climbing",
//   "fencing",
//   "boxing",
//   "judo",
//   "karate",
//   "taekwondo",
//   "olympic-wrestling",
//   "greco-roman-fight",
//   "professional-wrestling",
//   "kick-boxing",
//   "jiu-jitsu",
//   "muay-thai",
//   "full-contact",
//   "kung-fu",
//   "sumo",
//   "tai-chi",
//   "sambo",
//   "eskrima",
//   "fight-leonesa",
//   "canarian-wrestling",
//   "mixed-martial-arts",
//   "kendo",
//   "savate",
//   "lethwei",
//   "proresu",
//   "shoot-wrestling",
//   "shoot-fighting",
//   "saint-da",
//   "yagli-gures",
//   "capoeira",
//   "kenpo",
//   "hapkido",
//   "pa-kua-chang",
//   "ninjutsu",
//   "aikido",
//   "kenjutsu",
//   "wing chun",
//   "nanbudo",
//   "chess-boxing",
//   "pencak-silat",
//   "iaido",
//   "jeet-kune-do",
//   "tangsudo",
//   "taijutsu",
//   "side",
//   "schewingen",
//   "choy-li-fat",
//   "ssirum",
//   "bojutsu",
//   "shorinji kempo",
//   "kuntao",
//   "hakko-ryu",
//   "gatka",
//   "gouren",
//   "bokator",
//   "glima",
//   "football",
//   "beach-soccer",
//   "futsal",
//   "basketball",
//   "volleyball",
//   "beach-volleyball",
//   "water-polo",
//   "waterbasket.",
//   "handball",
//   "beach-handball",
//   "handball-at-11",
//   "rugby",
//   "beach-rugby",
//   "baseball.",
//   "hockey-grass",
//   "ice-hockey",
//   "hockey-skates",
//   "inline-roller-hockey.",
//   "indoor-hockey",
//   "beach-hockey",
//   "unicycle-hockey.",
//   "football.",
//   "softball.",
//   "lacrosse",
//   "cricket",
//   "tennikoit",
//   "curling",
//   "petanque.",
//   "bowls.",
//   "bowling.",
//   "australian-football.",
//   "gaelic-football.",
//   "pole.",
//   "polocrosse.",
//   "kayak-polo.",
//   "bike-polo.",
//   "padbol.",
//   "soccer-tennis.",
//   "futvolley.",
//   "tchoukball.",
//   "showbol",
//   "bandy",
//   "kickball",
//   "slamball",
//   "korfball.",
//   "kronum",
//   "floorball.",
//   "bossaball.",
//   "netball.",
//   "sepak-takraw.",
//   "broomball.",
//   "hurling.",
//   "shinty.",
//   "camogie.",
//   "indiaca.",
//   "pesapallo.",
//   "ultimate.",
//   "wallyball.",
//   "wiffle-ball.",
//   "underwater-football.",
//   "underwater-hockey.",
//   "underwater-rugby",
// ];
